<Project Sdk="Microsoft.NET.Sdk">

		<PropertyGroup>
				<TargetFrameworks>net472;net48;net8.0;net9.0</TargetFrameworks>
				<!-- 平台最低版本要求 -->
				<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-windows'))">10.0.19041.0</SupportedOSPlatformVersion>
				<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-android'))">21.0</SupportedOSPlatformVersion>
				<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-ios'))">14.2</SupportedOSPlatformVersion>
				<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-maccatalyst'))">15.0</SupportedOSPlatformVersion>
				<!-- 统一配置 .NET 6+ 共有的属性 -->
				<DefineConstants>$(DefineConstants);MODERN_DOTNET</DefineConstants>
				<LangVersion>10</LangVersion>
				<ImplicitUsings>enable</ImplicitUsings>
				<Nullable>enable</Nullable>
				<!--<PublishAot>true</PublishAot>-->
				<!--<IlcTrimMode>partial</IlcTrimMode>-->
				<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		</PropertyGroup>

		<!-- 若需要生成 Android/iOS/macOS，请在命令行追加 -p:ManySpeechIncludeMobileTargets=true -->
		<PropertyGroup Condition="'$(ManySpeechIncludeMobileTargets)' == 'true'">
				<TargetFrameworks>$(TargetFrameworks);net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
		</PropertyGroup>

		<PropertyGroup Condition="$([MSBuild]::IsOSPlatform('windows'))">
				<TargetFrameworks>$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
		</PropertyGroup>
		
		<ItemGroup>
				<PackageReference Include="LibGit2Sharp" Version="0.31.0" />
				<PackageReference Include="NAudio" Version="2.2.1" />
				<PackageReference Include="System.Net.Http" Version="4.3.4" Condition="'$(TargetFramework)' == 'netstandard2.0' OR '$(TargetFramework)' == 'netstandard2.1' OR '$(TargetFramework)' == 'netcoreapp3.1' OR '$(TargetFramework)' == 'net461' OR '$(TargetFramework)' == 'net472' OR '$(TargetFramework)' == 'net48'" />
		</ItemGroup>
		
</Project>
