<Project Sdk="Microsoft.NET.Sdk">

		<PropertyGroup>
				<TargetFrameworks>net461;net472;net48;netstandard2.0;netstandard2.1;netcoreapp3.1;net6.0;net8.0;net9.0</TargetFrameworks>
				<!-- 平台最低版本要求 -->
				<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-windows'))">10.0.19041.0</SupportedOSPlatformVersion>
				<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-android'))">21.0</SupportedOSPlatformVersion>
				<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-ios'))">14.2</SupportedOSPlatformVersion>
				<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-maccatalyst'))">15.0</SupportedOSPlatformVersion>
				<!-- 统一配置 .NET 6+ 共有的属性 -->
				<DefineConstants>$(DefineConstants);MODERN_DOTNET</DefineConstants>
				<LangVersion>10</LangVersion>
				<ImplicitUsings>enable</ImplicitUsings>
				<Nullable>enable</Nullable>
				<!--<PublishAot>true</PublishAot>-->
				<!--<IlcTrimMode>partial</IlcTrimMode>-->
				<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
				<!-- info -->
				<PackageId>AudioInOut</PackageId>
				<Version>1.0.0</Version>
				<Authors>manyeyes contributors</Authors>
				<Company>manyeyes contributors</Company>
				<Copyright>Copyright © manyeyes contributors</Copyright>
				<Summary>c# library for audio playback, recording, and processing, supporting Windows, Linux, and Mac platforms.</Summary>
				<Description>AudioInOut is based on NET's high-performance audio processing library provides cross platform audio playback, recording, and processing functions.</Description>
				<PackageTags>audio playback recording cross-platform</PackageTags>
				<PackageProjectUrl>https://github.com/manyeyes/ManySpeech</PackageProjectUrl>
				<RepositoryUrl>https://github.com/manyeyes/ManySpeech</RepositoryUrl>
				<IncludeSymbols>true</IncludeSymbols>
				<SymbolPackageFormat>snupkg</SymbolPackageFormat>
				<Nullable>enable</Nullable>
				<LangVersion>latest</LangVersion>
				<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
				<!--<PackageOutputPath>$(ArtifactsPath)\package</PackageOutputPath>-->
		</PropertyGroup>

		<!-- 若需要生成 Android/iOS/macOS，请在命令行追加 -p:ManySpeechIncludeMobileTargets=true -->
		<PropertyGroup Condition="'$(ManySpeechIncludeMobileTargets)' == 'true'">
				<TargetFrameworks>$(TargetFrameworks);net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
		</PropertyGroup>

		<PropertyGroup Condition="$([MSBuild]::IsOSPlatform('windows'))">
				<TargetFrameworks>$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
		</PropertyGroup>

		<!--<ItemGroup>
				<Page Include="rd.xaml">
						<Generator>MSBuild:Compile</Generator>
				</Page>
		</ItemGroup>-->

</Project>
