<Project Sdk="Microsoft.NET.Sdk">

		<PropertyGroup>
				<TargetFrameworks>net461;net472;net48;netstandard2.0;netstandard2.1;netcoreapp3.1;net6.0;net8.0;net9.0</TargetFrameworks>
				<!-- 平台最低版本要求 -->
				<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-windows'))">10.0.19041.0</SupportedOSPlatformVersion>
				<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-android'))">21.0</SupportedOSPlatformVersion>
				<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-ios'))">14.2</SupportedOSPlatformVersion>
				<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-maccatalyst'))">15.0</SupportedOSPlatformVersion>
				<!-- 统一配置 .NET 6+ 共有的属性 -->
				<DefineConstants>$(DefineConstants);MODERN_DOTNET</DefineConstants>
				<LangVersion>10.0</LangVersion>
				<ImplicitUsings>enable</ImplicitUsings>
				<Nullable>enable</Nullable>
				<!-- info -->
				<PackageId>ManySpeech.SpeechProcessing</PackageId>
				<Version>1.0.0</Version>
		</PropertyGroup>

		<!-- 若需要生成 Android/iOS/macOS，请在命令行追加 -p:ManySpeechIncludeMobileTargets=true -->
		<PropertyGroup Condition="'$(ManySpeechIncludeMobileTargets)' == 'true'">
				<TargetFrameworks>$(TargetFrameworks);net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
		</PropertyGroup>

		<PropertyGroup Condition="$([MSBuild]::IsOSPlatform('windows'))">
				<TargetFrameworks>$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
		</PropertyGroup>
		<ItemGroup>
				<PackageReference Include="ManySpeech.AliCTTransformerPunc" Version="1.0.6" />
				<PackageReference Include="ManySpeech.AliFsmnVad" Version="1.1.4" />
				<PackageReference Include="ManySpeech.AliParaformerAsr" Version="1.1.9" />
				<PackageReference Include="ManySpeech.FireRedAsr" Version="1.0.5" />
				<PackageReference Include="ManySpeech.K2TransducerAsr" Version="1.0.9" />
				<PackageReference Include="ManySpeech.MoonshineAsr" Version="1.1.1" />
				<PackageReference Include="ManySpeech.WenetAsr" Version="1.0.2" />
				<PackageReference Include="ManySpeech.WhisperAsr" Version="1.0.1" />
		</ItemGroup>
</Project>
